config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'
  devise_for :users

  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title, length: { maximum: 30 }

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]

  def index
    @notes = Note.order(id: :asc)
  end

  def show
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save!
      redirect_to root_path
      flash[:notice] = "ノートを作成しました"
    else
      redirect_to new_note_path
      flash[:alert] = "ノート作成に失敗しました"
    end
  end

  def edit
  end

  def update
    if @note.update_attributes(note_params)
      redirect_to root_path
    else
      redirect_to edit_path
    end
  end

  def destroy
    @note.destroy!
    redirect_to root_path
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :image).merge(user: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def max_width
    "mw-xl"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p>仮トップページです</p>
<button type="button" class="btn btn-primary">Primary</button>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        ©️SentenceNote(仮)2021
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <span class="navbar-brand">sentence note(仮)</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if user_signed_in? %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path %>
        <%= link_to "新規登録", new_user_registration_path %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light fixed-top" >
  <div class="container-fluid">
    <%= link_to "sentence note(仮)", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to edit_user_registration_path, class: 'nav-link' do %> 
              <i class="fas fa-user-circle"></i>
              <span class="mr-1">マイページ</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to root_path, class: 'nav-link' do %> 
              <i class="fas fa-book-open"></i>
              <span class="mr-1">一覧</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_note_path, class: "nav-link" do %>
              <i class="fas fa-edit"></i>
              <span class="mr-1">ノート作成</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } , class: 'nav-link' do %> 
              <i class="fas fa-sign-out-alt"></i>
              <span class="mr-1">ログアウト</span>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link' do %> 
            <i class="fas fa-id-card"></i>
            <span class="mr-1">アカウント登録</span>
          <% end %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link' do %> 
              <i class="fas fa-sign-in-alt"></i>
              <span class="mr-1">ログイン</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "#", class: 'nav-link' do %> 
              <i class="fas fa-user"></i>
              <span class="mr-1">ゲストログイン</span>
            <% end %>
          </li>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SentenceNoteApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <%= render "layouts/navbar" %>
        <%= render "layouts/flash" %>
      </header>
      <main>
          <%= yield %>
        </div>
      </main>
      <footer>
        <%= render "layouts/footer" %>
      </footer>
  </body>
</html>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<h1>ノート編集</h1>

app/views/notes/index.html.erb
<div class="container">
  <h4 class="title">ノート一覧<h4>
  <div class="row">
      <% @notes.each do |note| %>
        <div class="col-12 col-md-6 col-lg-4">
        <div class="card">
          <a href="#"><%= image_tag note.image.url %>
          <p class="note_title"><%= note.title %></p>
          </a>
          <div class="note_edit">
            <%= link_to edit_note_path(note), class: "item-edit" do %>
              <i class="fas fa-edit" title="編集"></i>
            <% end %>
            <%= link_to note_path(note),method: :delete, data: { confirm: "削除しますか？"}, class: "item-delete" do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </div>
        </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<%= form_with model: @note, local: true do |form| %>
  <p><%= form.text_field :title, placeholder: "タイトル" %></p>
  <p><%= form.file_field :image, accept: "image/png,image/jpeg,image/gif" %></p>
  <p><%= form.submit "保存" %></p>
<% end %>

app/views/notes/show.html.erb
<h1>Notes#show</h1>
<p>Find me in app/views/notes/show.html.erb</p>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>

app/views/users/show.html.erb
<p>ユーザーページ（仮）</p>